version: "3"
services:
  app:
    build:
      context: ./
    environment:
      APP_ENV: local
      DB_HOST: database
    networks:
      - islandfinder
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

  database:
    image: voyageapp/postgres:14.2
    ports:
      - "54325:5432"
    networks:
      - islandfinder
networks:
  islandfinder:
    driver: bridge
